#-----------------------------------------------------------------------
#   local 설정
#-----------------------------------------------------------------------
spring:
  datasource:
    hikari:
      # 9 server
      primary:
        database: mysql
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://211.119.124.9:4407/mens?useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&autoReconnect=true
        username: root
        password: xit1807
        read-only: false

  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,public/**
    livereload:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: info
    org.apache.http: warn
    io.netty: warn
    reactor.netty: WARN
    # webclient logging
    reactor.netty.http.client: DEBUG
    #org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework: warn
    org.hibernate.validator.internal: WARN
  file:
    # 로그파일 위치
    path: ${app.data.root.path}/mens/logs
    name: ${spring.application.name}

# ==================================================================================================================
# SQL logging lib setting
# ==================================================================================================================
decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
#      log-file:

app:
  api-ip: 211.119.124.73
  # 강제로 swagger-url을 지정해야 하는 경우만 선언
  #swagger-url: 'http://localhost:${server.port}${server.servlet.context-path:}/'
  # Spring Security cors 설정 :: CorsConfiguration 설정 값
  cors:
    allowed-origins: http://localhost:8080, http://${app.api-ip}:8080, http://localhost:8082, http://${app.api-ip}:8082

  data:
    root:
      #path: /Users/minuk/data
      path: d:/data

  #---------------------------------------------------------------
  # log 설정
  # request:
  #   custom-enabled | common-enabled | filter-enabled 중 1개만 활성화
  #   --> 운영: common-enabled, 개발: custom-enabled 사용 권장
  # response-enabled : 호출 결과 출력 - 운영시 false
  # mdc : api 호출(서비스) 로그 기록
  #   uris : api 호출 로그 제외 패턴
  #---------------------------------------------------------------
  log:
    request:
      custom-enabled: true
    response-enabled: true
    # MDC logging trace 활성
    mdc:
      enabled: false
